Project:
  project_name: AB95_combinedCatch_Lhemi_bestFit
  project_path: e:\Emily\sabatini-glm-workflow\projects\AB95_combinedCatch_Lhemi_bestFit
glm_params:
  glm_keyword_args:
    elasticnet:
      alpha: 1.0e-05
      cv: 5
      fit_intercept: true
      l1_ratio: 0.75
      max_iter: 1000
      n_alphas: 100
      n_jobs: -1
      score_metric: r2
      selection: cyclic
      warm_start: false
    linearregression:
      copy_X: true
      fit_intercept: true
      n_jobs: -1
      score_metric: r2
    ridge:
      alpha: 0.5
      cv: 5
      fit_intercept: true
      gcv_mode: auto
      max_iter: 1000
      n_jobs: -1
      score_metric: r2
      solver: auto
  predictors:
  - go
  - nogo
  - lick_1
  - lick_2
  - lick_3
  - lick_3R
  - lick_3C
  - last_lick
  - lick_non1-3
  - missReward
  - freeReward
  predictors_shift_bounds:
    freeReward:
    - -50
    - 50
    go:
    - 0
    - 100
    last_lick:
    - -20
    - 50
    lick_1:
    - -3
    - 50
    lick_2:
    - -5
    - 50
    lick_3:
    - -7
    - 50
    lick_3C:
    - -7
    - 50
    lick_3R:
    - -7
    - 50
    lick_non1-3:
    - -20
    - 50
    missReward:
    - -50
    - 50
    nogo:
    - 0
    - 100
  predictors_shift_bounds_default:
  - 0
  - 100
  regression_type: ElasticNet
  response: photometryLhemi
  type: Normal
train_test_split:
  test_size: 0.2
  train_size: 0.8
