Project:
  project_name: AB98_combinedFirst_Lhemi_bestFit
  project_path: e:\Emily\sabatini-glm-workflow\projects\AB98_combinedFirst_Lhemi_bestFit
glm_params:
  glm_keyword_args:
    elasticnet:
      alpha: 0.5
      cv: 5
      fit_intercept: true
      l1_ratio: 0.5
      max_iter: 1000
      n_alphas: 100
      n_jobs: -1
      score_metric: r2
      selection: cyclic
      warm_start: false
    linearregression:
      copy_X: true
      fit_intercept: true
      n_jobs: -1
      score_metric: r2
    ridge:
      alpha: 0.5
      cv: 5
      fit_intercept: true
      gcv_mode: auto
      max_iter: 1000
      n_jobs: -1
      score_metric: r2
      solver: auto
  predictors:
  - predictor1
  - predictor2
  - predictor3
  predictors_shift_bounds:
    predictor1:
    - -2
    - 2
    predictor2:
    - -2
    - 2
    predictor3:
    - -2
    - 2
  predictors_shift_bounds_default:
  - -50
  - 100
  regression_type: ridge
  response: photometryNI
  type: Normal
train_test_split:
  test_size: 0.2
  train_size: 0.8
